// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReversiHerkansing.Data;

namespace ReversiHerkansing.Migrations
{
    [DbContext(typeof(ReversiHerkansingContext))]
    [Migration("20220507074231_reversiinfo")]
    partial class reversiinfo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ReversiHerkansing.Model.Board", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Row00")
                        .HasColumnType("int");

                    b.Property<int>("Row01")
                        .HasColumnType("int");

                    b.Property<int>("Row02")
                        .HasColumnType("int");

                    b.Property<int>("Row03")
                        .HasColumnType("int");

                    b.Property<int>("Row04")
                        .HasColumnType("int");

                    b.Property<int>("Row05")
                        .HasColumnType("int");

                    b.Property<int>("Row06")
                        .HasColumnType("int");

                    b.Property<int>("Row07")
                        .HasColumnType("int");

                    b.Property<int>("Row10")
                        .HasColumnType("int");

                    b.Property<int>("Row11")
                        .HasColumnType("int");

                    b.Property<int>("Row12")
                        .HasColumnType("int");

                    b.Property<int>("Row13")
                        .HasColumnType("int");

                    b.Property<int>("Row14")
                        .HasColumnType("int");

                    b.Property<int>("Row15")
                        .HasColumnType("int");

                    b.Property<int>("Row16")
                        .HasColumnType("int");

                    b.Property<int>("Row17")
                        .HasColumnType("int");

                    b.Property<int>("Row20")
                        .HasColumnType("int");

                    b.Property<int>("Row21")
                        .HasColumnType("int");

                    b.Property<int>("Row22")
                        .HasColumnType("int");

                    b.Property<int>("Row23")
                        .HasColumnType("int");

                    b.Property<int>("Row24")
                        .HasColumnType("int");

                    b.Property<int>("Row25")
                        .HasColumnType("int");

                    b.Property<int>("Row26")
                        .HasColumnType("int");

                    b.Property<int>("Row27")
                        .HasColumnType("int");

                    b.Property<int>("Row30")
                        .HasColumnType("int");

                    b.Property<int>("Row31")
                        .HasColumnType("int");

                    b.Property<int>("Row32")
                        .HasColumnType("int");

                    b.Property<int>("Row33")
                        .HasColumnType("int");

                    b.Property<int>("Row34")
                        .HasColumnType("int");

                    b.Property<int>("Row35")
                        .HasColumnType("int");

                    b.Property<int>("Row36")
                        .HasColumnType("int");

                    b.Property<int>("Row37")
                        .HasColumnType("int");

                    b.Property<int>("Row40")
                        .HasColumnType("int");

                    b.Property<int>("Row41")
                        .HasColumnType("int");

                    b.Property<int>("Row42")
                        .HasColumnType("int");

                    b.Property<int>("Row43")
                        .HasColumnType("int");

                    b.Property<int>("Row44")
                        .HasColumnType("int");

                    b.Property<int>("Row45")
                        .HasColumnType("int");

                    b.Property<int>("Row46")
                        .HasColumnType("int");

                    b.Property<int>("Row47")
                        .HasColumnType("int");

                    b.Property<int>("Row50")
                        .HasColumnType("int");

                    b.Property<int>("Row51")
                        .HasColumnType("int");

                    b.Property<int>("Row52")
                        .HasColumnType("int");

                    b.Property<int>("Row53")
                        .HasColumnType("int");

                    b.Property<int>("Row54")
                        .HasColumnType("int");

                    b.Property<int>("Row55")
                        .HasColumnType("int");

                    b.Property<int>("Row56")
                        .HasColumnType("int");

                    b.Property<int>("Row57")
                        .HasColumnType("int");

                    b.Property<int>("Row60")
                        .HasColumnType("int");

                    b.Property<int>("Row61")
                        .HasColumnType("int");

                    b.Property<int>("Row62")
                        .HasColumnType("int");

                    b.Property<int>("Row63")
                        .HasColumnType("int");

                    b.Property<int>("Row64")
                        .HasColumnType("int");

                    b.Property<int>("Row65")
                        .HasColumnType("int");

                    b.Property<int>("Row66")
                        .HasColumnType("int");

                    b.Property<int>("Row67")
                        .HasColumnType("int");

                    b.Property<int>("Row70")
                        .HasColumnType("int");

                    b.Property<int>("Row71")
                        .HasColumnType("int");

                    b.Property<int>("Row72")
                        .HasColumnType("int");

                    b.Property<int>("Row73")
                        .HasColumnType("int");

                    b.Property<int>("Row74")
                        .HasColumnType("int");

                    b.Property<int>("Row75")
                        .HasColumnType("int");

                    b.Property<int>("Row76")
                        .HasColumnType("int");

                    b.Property<int>("Row77")
                        .HasColumnType("int");

                    b.Property<int>("SpelID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpelID");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("ReversiHerkansing.Model.ReversiInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Beurt")
                        .HasColumnType("int");

                    b.Property<int>("SpelId")
                        .HasColumnType("int");

                    b.Property<int>("Wit")
                        .HasColumnType("int");

                    b.Property<int>("Zwart")
                        .HasColumnType("int");

                    b.Property<int>("addWit")
                        .HasColumnType("int");

                    b.Property<int>("addZwart")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ReversiInfo");
                });

            modelBuilder.Entity("ReversiHerkansing.Model.Spel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AandeBeurt")
                        .HasColumnType("int");

                    b.Property<string>("Omschrijving")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Speler1Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Speler2Token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Spellen");
                });

            modelBuilder.Entity("ReversiHerkansing.Model.Board", b =>
                {
                    b.HasOne("ReversiHerkansing.Model.Spel", "Spel")
                        .WithMany()
                        .HasForeignKey("SpelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spel");
                });
#pragma warning restore 612, 618
        }
    }
}
